import moment from "moment";
import {CareType} from "../../../component/care/common/types";

const formatDate: string = "YYYY-MM-DD";
const formatHourTime: string = "HH:00";

export const InitialCare: CareType = {
    jobType: "",
    requestType: "",
    familyId: 0,
    coronaCheck: 0,
    startDate: moment().format(formatDate),
    startTime: moment(moment().subtract(-1, "hours")).format(formatHourTime),
    endDate: moment(moment().add(7, "days")).format(formatDate),
    endTime: moment(moment().subtract(-1, "hours")).format(formatHourTime),
    selectOption: 1,
    selectDate: moment().format(formatDate),
    name: "",
    gender: 0,
    weight: "",
    height: "",
    age: "",
    sickroomType: 0,
    paralysis: 0,
    consciousness: 0,
    cognitive: 4,
    cognitiveDementiaEtc: "",
    cognitiveDeliriumEtc: "",
    moveToilet: 0,
    moveToiletEtc: "",
    stoma: 0,
    toiletType: 4,
    toiletDiapersEtc: "",
    toiletLineEtc: "",
    somnipathy: 0,
    somnipathyEtc: "",
    suction: 0,
    rehabilitate: 0,
    dialysis: 0,
    changePosture: 0,
    eat: 0,
    feeding: 0,
    move: 0,
    favoriteGender: 0,
    hospitalizeReason: "",
    infectiousDisease: 64,
    infectiousDiseaseEtc: "",
    diagnosis: "",
    isWantUniform: "Y",
    hospitalId: 0,
    info: "",
    detail: "",
    address: "",
    addressNameArr: "",
    lat: 0,
    lon: 0,
    hosCode: "",
    locCode: "",
    siCode: "",
    guCode: ""
};
